# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatRoom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChatRoom.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x43hatRoom.proto\"5\n\x0fJoinChatRequest\x12\x10\n\x08roomname\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"7\n\x11\x43reateChatRequest\x12\x10\n\x08roomname\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x0fNicknameRequest\x12\x10\n\x08nickname\x18\x01 \x01(\t\"0\n\x0bSendMessage\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rEmptyResponse\"\x1e\n\rStateResponse\x12\r\n\x05state\x18\x01 \x01(\t2\xd7\x01\n\x0b\x43hatService\x12.\n\x08JoinChat\x12\x10.JoinChatRequest\x1a\x0c.SendMessage\"\x00\x30\x01\x12.\n\x0csendMenssage\x12\x0c.SendMessage\x1a\x0e.EmptyResponse\"\x00\x12\x32\n\nCreateChat\x12\x12.CreateChatRequest\x1a\x0e.StateResponse\"\x00\x12\x34\n\x0einformNickname\x12\x10.NicknameRequest\x1a\x0e.StateResponse\"\x00\x62\x06proto3')
)




_JOINCHATREQUEST = _descriptor.Descriptor(
  name='JoinChatRequest',
  full_name='JoinChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomname', full_name='JoinChatRequest.roomname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='JoinChatRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=71,
)


_CREATECHATREQUEST = _descriptor.Descriptor(
  name='CreateChatRequest',
  full_name='CreateChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomname', full_name='CreateChatRequest.roomname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='CreateChatRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=128,
)


_NICKNAMEREQUEST = _descriptor.Descriptor(
  name='NicknameRequest',
  full_name='NicknameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='NicknameRequest.nickname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=165,
)


_SENDMESSAGE = _descriptor.Descriptor(
  name='SendMessage',
  full_name='SendMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='SendMessage.nickname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='SendMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=215,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=232,
)


_STATERESPONSE = _descriptor.Descriptor(
  name='StateResponse',
  full_name='StateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='StateResponse.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['JoinChatRequest'] = _JOINCHATREQUEST
DESCRIPTOR.message_types_by_name['CreateChatRequest'] = _CREATECHATREQUEST
DESCRIPTOR.message_types_by_name['NicknameRequest'] = _NICKNAMEREQUEST
DESCRIPTOR.message_types_by_name['SendMessage'] = _SENDMESSAGE
DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
DESCRIPTOR.message_types_by_name['StateResponse'] = _STATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinChatRequest = _reflection.GeneratedProtocolMessageType('JoinChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINCHATREQUEST,
  '__module__' : 'ChatRoom_pb2'
  # @@protoc_insertion_point(class_scope:JoinChatRequest)
  })
_sym_db.RegisterMessage(JoinChatRequest)

CreateChatRequest = _reflection.GeneratedProtocolMessageType('CreateChatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHATREQUEST,
  '__module__' : 'ChatRoom_pb2'
  # @@protoc_insertion_point(class_scope:CreateChatRequest)
  })
_sym_db.RegisterMessage(CreateChatRequest)

NicknameRequest = _reflection.GeneratedProtocolMessageType('NicknameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NICKNAMEREQUEST,
  '__module__' : 'ChatRoom_pb2'
  # @@protoc_insertion_point(class_scope:NicknameRequest)
  })
_sym_db.RegisterMessage(NicknameRequest)

SendMessage = _reflection.GeneratedProtocolMessageType('SendMessage', (_message.Message,), {
  'DESCRIPTOR' : _SENDMESSAGE,
  '__module__' : 'ChatRoom_pb2'
  # @@protoc_insertion_point(class_scope:SendMessage)
  })
_sym_db.RegisterMessage(SendMessage)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYRESPONSE,
  '__module__' : 'ChatRoom_pb2'
  # @@protoc_insertion_point(class_scope:EmptyResponse)
  })
_sym_db.RegisterMessage(EmptyResponse)

StateResponse = _reflection.GeneratedProtocolMessageType('StateResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATERESPONSE,
  '__module__' : 'ChatRoom_pb2'
  # @@protoc_insertion_point(class_scope:StateResponse)
  })
_sym_db.RegisterMessage(StateResponse)



_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='ChatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=267,
  serialized_end=482,
  methods=[
  _descriptor.MethodDescriptor(
    name='JoinChat',
    full_name='ChatService.JoinChat',
    index=0,
    containing_service=None,
    input_type=_JOINCHATREQUEST,
    output_type=_SENDMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendMenssage',
    full_name='ChatService.sendMenssage',
    index=1,
    containing_service=None,
    input_type=_SENDMESSAGE,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateChat',
    full_name='ChatService.CreateChat',
    index=2,
    containing_service=None,
    input_type=_CREATECHATREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='informNickname',
    full_name='ChatService.informNickname',
    index=3,
    containing_service=None,
    input_type=_NICKNAMEREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
