# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ChatRoom_pb2 as ChatRoom__pb2


class ChatServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.JoinChat = channel.unary_stream(
        '/ChatService/JoinChat',
        request_serializer=ChatRoom__pb2.JoinChatRequest.SerializeToString,
        response_deserializer=ChatRoom__pb2.SendMessage.FromString,
        )
    self.sendMenssage = channel.unary_unary(
        '/ChatService/sendMenssage',
        request_serializer=ChatRoom__pb2.SendMessage.SerializeToString,
        response_deserializer=ChatRoom__pb2.EmptyResponse.FromString,
        )
    self.CreateChat = channel.unary_unary(
        '/ChatService/CreateChat',
        request_serializer=ChatRoom__pb2.CreateChatRequest.SerializeToString,
        response_deserializer=ChatRoom__pb2.StateResponse.FromString,
        )
    self.informNickname = channel.unary_unary(
        '/ChatService/informNickname',
        request_serializer=ChatRoom__pb2.NicknameRequest.SerializeToString,
        response_deserializer=ChatRoom__pb2.StateResponse.FromString,
        )


class ChatServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def JoinChat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendMenssage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateChat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def informNickname(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'JoinChat': grpc.unary_stream_rpc_method_handler(
          servicer.JoinChat,
          request_deserializer=ChatRoom__pb2.JoinChatRequest.FromString,
          response_serializer=ChatRoom__pb2.SendMessage.SerializeToString,
      ),
      'sendMenssage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMenssage,
          request_deserializer=ChatRoom__pb2.SendMessage.FromString,
          response_serializer=ChatRoom__pb2.EmptyResponse.SerializeToString,
      ),
      'CreateChat': grpc.unary_unary_rpc_method_handler(
          servicer.CreateChat,
          request_deserializer=ChatRoom__pb2.CreateChatRequest.FromString,
          response_serializer=ChatRoom__pb2.StateResponse.SerializeToString,
      ),
      'informNickname': grpc.unary_unary_rpc_method_handler(
          servicer.informNickname,
          request_deserializer=ChatRoom__pb2.NicknameRequest.FromString,
          response_serializer=ChatRoom__pb2.StateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChatService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
